### ISSUE TITLE
Jenkins WAR version in POM is overridden by transitive plugin dependency

### ISSUE THREAD

**Issue by andreyakostov** [jenkinsci/custom-war-packager#126]
packager-config.yml:
```yml
bundle:
  groupId: com.test
  artifactId: jenkins
  vendor: andreyakostov
buildSettings:
  pom: pom.xml
  pomIgnoreRoot: true
  pomIncludeWar: true
```

pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.test</groupId>
  <artifactId>jenkins-plugins</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <properties>
    <jenkins.version>2.190.1</jenkins.version>
    <java.level>8</java.level>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>resource-disposer</artifactId>
      <version>0.13</version>
    </dependency>
  </dependencies>

</project>
```

`resource-disposer` depends on jenkins-core 2.54, which overrides the version specified in the `jenkins.version` property.
