### ISSUE TITLE
YAML parser does not honor YAML anchors in definition

### ISSUE THREAD

**Issue by MarkSRobinson** [jenkinsci/custom-war-packager#151]
When using the YAML config file in v1.7 it appears that it does correctly process YAML anchors.

```
  - groupId: "io.jenkins.blueocean"
    artifactId: "blueocean"
    source:
      version: &blueocean_version
          "1.22.0"
  - groupId: "io.jenkins.blueocean"
    artifactId: "blueocean-web"
    source:
      version: *blueocean_version
  - groupId: "io.jenkins.blueocean"
    artifactId: "blueocean-web"
    source:
      version: *blueocean_version
```

Should correctly process all three plugins to version 1.22.0, instead you get the error  `The POM for io.jenkins.blueocean:blueocean-web:jar:blueocean_version is missing, no dependency information available`
